区分浏览器环境和webpack打包
hizzgdev/jsmind pull request #351
Opened 2022-06-16 15:51 UTC by MTTTM

**添加区分浏览器环境和webpack环境的rollup打包**

**修改内容:**

1. rollup.config.js
2. src/plugins
3. README.MD

2022-06-16 17:05 UTC, hizzgdev requested changes
首先感谢 @MTTTM 的贡献，动手很快，令人敬佩。

不过目前es6这个版本还是个测试版，暂时不合适直接拿来替换原来的版本。所以你可以看到在es6版本的应用上并没有一刀切。

另外你可能需要同步修改一下2_features_es6.html 这个文件，然后点一下里面的按钮，都测试一下。

最后我在CI的task上配置代码的格式化检查不知道这个pr为什么没跑。

2022-06-16 17:05 UTC, hizzgdev commented on .config/rollup.config.js
> -            format: 'iife',
iife模式下生成的代码也是可以import的啊，为什么要单独生成个cjs版本的呢？

2022-06-16 17:05 UTC, hizzgdev commented on .config/rollup.config.js
> +            sourcemap: false,
如果不生成map文件，调试的时候就不方便了。如果不想把map文件放到代码库里，我们可以考虑其他的办法，比如代码库只放源文件，生成的min及source map发布到另外的地方。

2022-06-16 17:05 UTC, hizzgdev commented on .config/rollup.config.js
> +            file: 'js/jsmind.js',
es6的版本还正在测试阶段，目前暂时不要替换/js目录里的版本

2022-06-16 17:05 UTC, hizzgdev commented on package.json
> +    "main": "es6/jsmind.js",
先不要这么做，等es版本的稳定了再切

2022-06-17 02:41 UTC, MTTTM commented on .config/rollup.config.js
> -            format: 'iife',
1.因为打包用umd模式时候，
要求暴露个全局变量（针对<script>引入的方式）
但是目前`插件`目录里面的代码是这样的，并不需要暴露全局变量
`(function(){/*马上执行函数*/})(window,jsmind);`
2.script引入的插件代码是马上运行函数的，但是ES6的不是

基于上面2个原因，我觉得入口分开&&iife再执行ES6里面函数可能会更加方便维护

2022-06-17 02:52 UTC, MTTTM commented on .config/rollup.config.js
> +            sourcemap: false,
嗯，我明白你的意思，开发环境和生产环境的配置，最好分开下哦，这样感觉会更加方便点
用rollup-plugin-serve搭建本地服务器，rollup-plugin-livereload来监听文件变化刷新浏览器，我目前用这个很舒适

2022-06-20 16:03 UTC, ttsdzzg commented on .config/rollup.config.js
> -            format: 'iife',
嗯，了解你的想法了。之前没注意你是给插件改的 format。
关于插件，我的想法是只有在开发插件的时候，才有可能需要 import, 而在使用它的时候，不应该去 import 它。可以设想一下如果需要 import 插件的话，还需要怎么做才能 enable 这个插件。

2022-06-20 16:06 UTC, ttsdzzg commented on .config/rollup.config.js
> +            sourcemap: false,
感谢你的建议，后面我会考虑再加一个“开发文档”来介绍如何在 ES6 模式下开发 jsmind 及插件。
但对于 jsmind 的使用者来说，我们可能并不能假设大家都会在项目里使用 node。

2022-06-20 16:07 UTC, hizzgdev commented on .config/rollup.config.js
> -            format: 'iife',
嗯，了解你的想法了。之前没注意你是给插件改的 format。
关于插件，我的想法是只有在开发插件的时候，才有可能需要 import, 而在使用它的时候，不应该去 import 它。可以设想一下如果需要 import 插件的话，还需要怎么做才能 enable 这个插件。

2022-06-20 16:07 UTC, hizzgdev commented on .config/rollup.config.js
> +            sourcemap: false,
感谢你的建议，后面我会考虑再加一个“开发文档”来介绍如何在 ES6 模式下开发 jsmind 及插件。
但对于 jsmind 的使用者来说，我们可能并不能假设大家都会在项目里使用 node。

2022-07-19 13:37 UTC, closed without merging